import { NextRequest, NextResponse } from 'next/server';
import { readFileSync, existsSync } from 'fs';
import { join, normalize } from 'path';

export const runtime = 'nodejs';

// Get images directory path
const projectRoot = process.cwd().includes('packages/dashboard')
  ? join(process.cwd(), '..', '..')
  : process.cwd();

const IMAGES_DIR = process.env.IMAGES_DIR || join(projectRoot, 'data', 'images');

const MIME_TYPES: Record<string, string> = {
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  webp: 'image/webp',
  gif: 'image/gif',
};

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ path: string[] }> }
) {
  try {
    const { path } = await params;
    const imagePath = path.join('/');

    // Decode the path (it may be URL encoded)
    const decodedPath = decodeURIComponent(imagePath);

    // Normalize and resolve the full path
    let fullPath: string;

    if (decodedPath.startsWith('/')) {
      // Absolute path provided - use directly but verify it's in allowed directory
      fullPath = normalize(decodedPath);
    } else {
      // Relative path - resolve from images directory
      fullPath = normalize(join(IMAGES_DIR, decodedPath));
    }

    // Security: ensure path is within the images directory or is an absolute path
    // that was generated by our system
    const isInImagesDir = fullPath.startsWith(normalize(IMAGES_DIR));
    const isValidAbsolutePath = fullPath.includes('/data/images/') || fullPath.includes('\\data\\images\\');

    if (!isInImagesDir && !isValidAbsolutePath) {
      return new NextResponse('Forbidden', { status: 403 });
    }

    if (!existsSync(fullPath)) {
      return new NextResponse('Not found', { status: 404 });
    }

    const imageData = readFileSync(fullPath);
    const extension = fullPath.split('.').pop()?.toLowerCase() || 'png';
    const mimeType = MIME_TYPES[extension] || 'image/png';

    return new NextResponse(imageData, {
      headers: {
        'Content-Type': mimeType,
        'Cache-Control': 'public, max-age=31536000, immutable',
      },
    });
  } catch (error) {
    console.error('Image serving error:', error);
    return new NextResponse('Internal error', { status: 500 });
  }
}
